export const SUCCESS = 'SUCCESS'
export const VALIDATION_ERROR = 'VALIDATION_ERROR'

export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'


export const VALIDATE_ADD_TODO = 'VALIDATE_ADD_TODO'
export const CLEAR_ADD_TODO_TITLE_ERROR = 'CLEAR_ADD_TODO_TITLE_ERROR'
export const CLEAR_ADD_TODO_DESCRIPTION_ERROR = 'CLEAR_ADD_TODO_DESCRIPTION_ERROR'
export const CLEAR_ADD_TODO_STATE = 'CLEAR_ADD_TODO_STATE'


